import { Sequelize } from 'sequelize';
import {
  BelongsTo,
  Column,
  DataType,
  ForeignKey,
  HasMany,
  Model,
  Table,
} from 'sequelize-typescript';
import { EmailStatusSenderTypeList } from '../../../const';

export interface EmailTransactionAttributes {
  id: string;
  sendFrom: string;
  sendTo: string;
  sendCc: string;
  sendSubject: string;
  sendType: string;
  sendParam: any;
  sendAt?: Date
  sendMessage?: string;
  status?: typeof EmailStatusSenderTypeList[number];
  createdBy: string;
  createdAt: Date;
  updatedAt?: Date;
  deletedAt?: Date;
  companyId?: string;
  companyInfo?: any;
}

type EmailTransactionAutoGeneratedAttributes =
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'deletedAt';
export type EmailTransactionCreationAttributes = Omit<
  EmailTransactionAttributes,
  EmailTransactionAutoGeneratedAttributes
>;

@Table({
  freezeTableName: true,
  tableName: 'mail_transaction',
  underscored: true,
  paranoid: true,
  schema: 'transaction',
})
class EmailTransaction
  extends Model<EmailTransactionAttributes | EmailTransactionCreationAttributes>
  implements EmailTransactionAttributes {

  @Column({
    allowNull: false,
    type: DataType.STRING,
    defaultValue: Sequelize.literal('uuid_generate_v7()'),
    primaryKey: true,
  })
  id!: string;

  @Column({
    allowNull: true,
    type: DataType.STRING,
  })
  sendFrom!: string;

  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  sendTo!: string;

  @Column({
    allowNull: true,
    type: DataType.STRING,
  })
  sendCc!: string;

  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  sendSubject!: string;

  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  sendType!: string;

  @Column({
    allowNull: true,
    type: DataType.DATE,
  })
  sendAt!: Date;

  @Column({
    allowNull: true,
    type: DataType.TEXT,
  })
  sendMessage!: string;

  @Column({
    allowNull: false,
    type: DataType.ENUM(...EmailStatusSenderTypeList),
    defaultValue: "DRAFT"
  })
  status!: typeof EmailStatusSenderTypeList[number]

  @Column({
    type: DataType.JSONB,
    get() {
      try {
        return JSON.parse(this.getDataValue('sendParam'));
      } catch (error) {
        return this.getDataValue('sendParam');
      }
    },
  })
  sendParam!: any;

  @Column({
    allowNull: true,
    type: DataType.STRING,
  })
  companyId?: string;

  @Column({
    allowNull: true,
    type: DataType.JSONB,
  })
  companyInfo?: any;

  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  createdBy!: string;

  @Column({
    allowNull: false,
    type: DataType.DATE,
    defaultValue: Sequelize.literal('now()'),
  })
  createdAt!: Date;

  @Column({
    type: DataType.DATE,
  })
  updatedAt!: Date;

  @Column({
    type: DataType.DATE,
  })
  deletedAt!: Date;

}

export default EmailTransaction;
