import { Sequelize } from 'sequelize';
import {
  BelongsTo,
  Column,
  DataType,
  ForeignKey,
  HasOne,
  Model,
  Table,
} from 'sequelize-typescript';
import Users from './Users';
import Roles from '../master/MasterRole';
import MasterMenuItems from '../master/MasterMenuItems';

export interface RoleMenusAttributes {
  id: number;
  menusId: number;
  roleId: number;
  act_views?: boolean;
  act_reads?: boolean;
  act_create?: boolean;
  act_update?: boolean;
  act_delete?: boolean;
  act_denied?: boolean;
  flag?: number;
  createdBy: string;
  createdAt: Date;
  updatedBy?: string;
  updatedAt?: Date;
  deletedAt?: Date;
}

type RoleMenusAutoGeneratedAttributes =
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'deletedAt';
export type RoleMenusCreationAttributes = Omit<
  RoleMenusAttributes,
  RoleMenusAutoGeneratedAttributes
>;

@Table({
  freezeTableName: true,
  tableName: 'role_menus',
  paranoid: true,
  schema: 'credentials',
  underscored: true,
})
class RoleMenus
  extends Model<RoleMenusAttributes | RoleMenusCreationAttributes>
  implements RoleMenusAttributes {
  @Column({
    primaryKey: true,
    type: DataType.NUMBER,
    autoIncrement: true,
  })
  id!: number;

  @ForeignKey(() => MasterMenuItems)
  @Column({
    allowNull: false,
    type: DataType.BIGINT,
  })
  menusId!: number;

  @ForeignKey(() => Roles)
  @Column({
    allowNull: false,
    type: DataType.BIGINT,
  })
  roleId!: number;

  @Column({
    allowNull: true,
    type: DataType.BOOLEAN,
    defaultValue: false,
  })
  act_views!: boolean;

  @Column({
    allowNull: true,
    type: DataType.BOOLEAN,
    defaultValue: false,
  })
  act_reads!: boolean;

  @Column({
    allowNull: true,
    type: DataType.BOOLEAN,
    defaultValue: false,
  })
  act_create!: boolean;

  @Column({
    allowNull: true,
    type: DataType.BOOLEAN,
    defaultValue: false,
  })
  act_update!: boolean;

  @Column({
    allowNull: true,
    type: DataType.BOOLEAN,
    defaultValue: false,
  })
  act_delete!: boolean;

  @Column({
    allowNull: true,
    type: DataType.BOOLEAN,
    defaultValue: true,
  })
  act_denied!: boolean;

  @Column({
    allowNull: true,
    type: DataType.INTEGER,
    defaultValue: 1,
  })
  flag!: number;

  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  createdBy!: string;

  @Column({
    allowNull: false,
    type: DataType.DATE,
    defaultValue: Sequelize.literal('now()'),
  })
  createdAt!: Date;

  @Column({
    allowNull: true,
    type: DataType.STRING,
  })
  updatedBy!: string;

  @Column({
    type: DataType.DATE,
  })
  updatedAt!: Date;

  @Column({
    type: DataType.DATE,
  })
  deletedAt!: Date;


  @BelongsTo(() => Roles, {
    onDelete: 'cascade',
    onUpdate: 'cascade',
  })
  role!: Roles;

  @BelongsTo(() => MasterMenuItems, {
    onDelete: 'cascade',
    onUpdate: 'cascade',
  })
  menu!: MasterMenuItems;
}

export default RoleMenus;
