import {
  BelongsTo,
  Column,
  DataType,
  ForeignKey,
  HasMany,
  HasOne,
  Index,
  Model,
  Table,
} from 'sequelize-typescript';
import { Sequelize } from 'sequelize';
import UserRoles from './UserRole';
import Users from './Users';

export interface UsersAssigmentAttributes {
  id: string;
  userId: string;
  createdBy: string;
  createdAt: Date;
  updatedBy?: string;
  updatedAt?: Date;
  deletedAt?: Date;
}

type UsersAssigmentAutoGeneratedAttributes =
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'deletedAt';
export type UsersAssigmentCreationAttributes = Omit<
  UsersAssigmentAttributes,
  UsersAssigmentAutoGeneratedAttributes
>;

@Table({
  freezeTableName: true,
  tableName: 'users_assigment',
  paranoid: true,
  schema: 'credentials',
  underscored: true,
})
class UsersAssigment
  extends Model<UsersAssigmentAttributes | UsersAssigmentCreationAttributes>
  implements UsersAssigmentAttributes {
  @Column({
    allowNull: false,
    type: DataType.STRING,
    defaultValue: Sequelize.literal('uuid_generate_v7()'),
    primaryKey: true,
  })
  id!: string;

  @ForeignKey(() => Users)
  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  userId!: string;



  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  createdBy!: string;

  @Column({
    type: DataType.DATE,
    defaultValue: Sequelize.literal('now()'),
  })
  createdAt!: Date;

  @Column({
    allowNull: false,
    type: DataType.STRING,
  })
  updatedBy!: string;

  @Column({
    type: DataType.DATE,
    defaultValue: Sequelize.literal('now()'),
  })
  updatedAt!: Date;

  @Column({
    type: DataType.DATE,
  })
  deletedAt!: Date;

  @BelongsTo(() => Users, {
    targetKey: "id",
    onDelete: 'cascade',
    onUpdate: 'cascade',
  })
  userInfo!: Users;


}

export default UsersAssigment;
